# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'ModelTester' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ModelTester
  pod "onnxruntime-c"

  target 'ModelTesterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ModelTesterUITests' do
    # Pods for testing
  end

end
