jobs:

- job: compliance
  pool:
    vmImage: "windows-2019"
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.8.x'

  - powershell: |
     &C:\vcpkg\vcpkg.exe install protobuf:x64-windows-static
     $Env:USE_MSVC_STATIC_RUNTIME=1
     $Env:ONNX_ML=1
     $Env:CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=OFF -DProtobuf_USE_STATIC_LIBS=ON -DONNX_USE_LITE_PROTO=ON -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static"          
     python -m pip --disable-pip-version-check install -r $(Build.SourcesDirectory)\mobile\examples\speech_recognition\model\requirements.txt

    displayName: 'PowerShell Script'

  - task: PoliCheck@2
    displayName: 'Run Global Readiness Check tool'
    inputs:
      targetType: F
      result: PoliCheck.xml
      optionsUEPATH: '$(Build.SourcesDirectory)\ci_build\policheck_exclusions.xml'


  - task: Semmle@1
    displayName: 'Run CodeQL (Semmle) (python)'
    inputs:
      language: python

  - task: SdtReport@2
    displayName: 'Create Security Analysis Report'
    inputs:
      GdnExportAllTools: false
      GdnExportGdnToolPoliCheck: true
      GdnExportGdnToolSemmle: true

  - task: PublishSecurityAnalysisLogs@3
    displayName: 'Publish Guardian Artifacts'

  - task: TSAUpload@2
    displayName: 'TSA upload'
    condition: and (succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      GdnPublishTsaOnboard: false
      GdnPublishTsaConfigFile: '$(Build.SourcesDirectory)\.gdn\.gdntsa'
