$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: question-answer-ort
model: azureml:bert-large-uncased-whole-word-masking-finetuned-squad:3
code_configuration:
  code: ../
  scoring_script: score.py
environment:
  conda_file: env.yml
  image: mcr.microsoft.com/azureml/openmpi3.1.2-cuda10.2-cudnn8-ubuntu18.04
instance_type: Standard_NC6s_v3
instance_count: 1