platform :ios, '11.0'

target 'ORTSuperResolution' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OrtSuperResolution
  pod 'onnxruntime-c'
  
  # Release version pod for ort-ext
  pod 'onnxruntime-extensions-c', '0.6.0'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    end
  end
end

