platform :ios, '13.0'

target 'ORTObjectDetection' do
  use_frameworks!

  # Pods for ORTObjectDetection
  pod 'onnxruntime-objc'

  target 'ORTObjectDetectionTests' do
    inherit! :search_paths
  end
end
