platform :ios, '13.0'

target 'ORTQuestionAnswering' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ORTQuestionAnswering
  pod 'onnxruntime-c'
  
  pod 'onnxruntime-extensions-c'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    end
  end
end
