name: Node.js CI
permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        # Test against multiple Node.js versions
        node-version: [20.x, 22.x, 24.x]
        arch: [x64]
        include:
          - os: ubuntu-latest
            arch: arm64
    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.arch }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
        architecture: ${{ matrix.arch }}
    - name: Install dependencies
      run: npm install
      working-directory: js/quick-start_onnxruntime-node
      
    - name: Run the example
      run: node .
      working-directory: js/quick-start_onnxruntime-node